In [1]:
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# heights (cm)
X = np.array([[147, 150, 153, 158, 163, 165, 168, 170, 173, 175, 178, 180, 183]]).T

# weight
y = np.array([ 49, 50, 51, 54, 58, 59, 60, 62, 63, 64, 66, 67, 68])

In [3]:
one = np.ones((X.shape[0], 1))
Xbar = np.concatenate((one, X), axis=1)

In [4]:
one

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [6]:
Xbar

array([[  1., 147.],
       [  1., 150.],
       [  1., 153.],
       [  1., 158.],
       [  1., 163.],
       [  1., 165.],
       [  1., 168.],
       [  1., 170.],
       [  1., 173.],
       [  1., 175.],
       [  1., 178.],
       [  1., 180.],
       [  1., 183.]])

In [9]:
A = np.dot(Xbar.T, Xbar)
b = np.dot(Xbar.T, y)

w = np.dot(np.linalg.pinv(A), b)

In [10]:
w_0, w_1 = w[0], w[1]

In [11]:
w

array([-33.73541021,   0.55920496])

In [13]:
y1 = w_1 * 155 + w_0
y2 = w_1 * 160 + w_0

print(f"With height is 155 cm, predicted weight is {y1}.")
print(f"With height is 160 cm, predicted weight is {y2}.")

With height is 155 cm, predicted weight is 52.94135889480448.
With height is 160 cm, predicted weight is 55.73738370451747.


# Thực hiện theo sklearn

In [14]:
from sklearn import datasets, linear_model

regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression()

In [15]:
print(f"Sklearn  w_1 = {regr.coef_[0]}, w_0 = {regr.intercept_}.")
print(f"Manually w_1 = {w_1}, w_0 = {w_0}.")

Sklearn  w_1 = 0.5592049619396674, w_0 = -33.73541020580774.
Manually w_1 = 0.5592049619425978, w_0 = -33.735410206298184.
